name: Release Drafter

#on:
#  push:
#    # branches to consider in the event; optional, defaults to all
#    branches:
#      - dev

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      # Drafts your next release notes based on merged pull requests
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
