name: validate code quality workflow
on:
  pull_request:
    branches:
      - main
jobs:
  code_quality:
    name: test code quality
    runs-on: ubuntu-latest
    steps:
      - name: repository checkout step
        uses: actions/checkout@v4
      - name: python environment step
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: install pre-commit
        run: python3 -m pip install pre-commit
      - id: changed-files
        name: identify modified files
        uses: tj-actions/changed-files@v40
      - name: run pre-commit hooks on modified files
        run: pre-commit run --color always --files ${{ steps.changed-files.outputs.all_changed_files }} --show-diff-on-failure
      - name: check missing __init__ files
        run: build_tools/fail_on_missing_init_files.sh
        shell: bash
  detect:
    name: detect changes
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      components: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            datasets:
              - sktime/base/**
              - sktime/datasets/**
            pyproject:
              - pyproject.toml
  test_install_extras:
    needs: detect
    name: validate extra installs
    if: ${{ needs.detect.outputs.pyproject == 'true' }}
    uses: ./.github/workflows/validate_extras.yml
  unit_test_base:
    needs: code_quality
    name: run unit tests for base framework
    uses: ./.github/workflows/test_base.yml
  unit_test_components:
    needs: code_quality
    name: run unit tests for individual components
    uses: ./.github/workflows/test_components.yml
  unit_test_datasets:
    needs: detect
    name: run unit tests for datasets
    if: ${{ needs.detect.outputs.datasets == 'true' }}
    uses: ./.github/workflows/validate_datasets.yml
