name: test individual components workflow
on:
  pull_request:
    branches:
      - main
jobs:
  detect:
    name: check for changes in individual components
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      components: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            alignment:
              - sktime/alignment/**
            annotation:
              - sktime/annotation/**
            classification:
              - sktime/classification/**
            clustering:
              - sktime/clustering/**
            forecasting:
              - sktime/forecasting/**
            networks:
              - sktime/networks/**
            param_est:
              - sktime/param_est/**
            regression:
              - sktime/regression/**
            transformations:
              - sktime/transformations/**
  test:
    needs: detect
    name: test specific component
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
        operating-system:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        sktime-component: ${{ fromJSON(needs.detect.outputs.components) }}
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: run tests for component ${{ matrix.sktime-component }} on python ${{ matrix.python-version }}
        uses: ./.github/actions/test-component
        with:
          sktime-component-identifier: ${{ matrix.sktime-component }}
          python-version-identifier: ${{ matrix.python-version }}
