name: test modules
on:
  workflow_call:
jobs:
  detect:
    name: detect change in module
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      components: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            alignment:
              - sktime/base/**
              - sktime/alignment/**
            annotation:
              - sktime/base/**
              - sktime/annotation/**
            classification:
              - sktime/base/**
              - sktime/classification/**
            clustering:
              - sktime/base/**
              - sktime/clustering/**
            forecasting:
              - sktime/base/**
              - sktime/forecasting/**
            networks:
              - sktime/base/**
              - sktime/networks/**
            param_est:
              - sktime/base/**
              - sktime/param_est/**
            regression:
              - sktime/base/**
              - sktime/regression/**
            transformations:
              - sktime/base/**
              - sktime/transformations/**
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
  test:
    needs: detect
    name: test module
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
        operating-system:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        sktime-component: ${{ fromJSON(needs.detect_components_with_extras.outputs.components) }}
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: checkout pull request branch
        uses: actions/checkout@v4
      - name: run tests for component ${{ matrix.sktime-component }} on python ${{ matrix.python-version }}
        uses: ./.github/actions/test-component
        with:
          sktime-component-identifier: ${{ matrix.sktime-component }}
          python-version-identifier: ${{ matrix.python-version }}
          sub-sample-estimators: "True"
          test-affected-estimators: "True"
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
  detect_components_without_extras:
    name: check for changes in individual components without extras
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      components_without_extras: ${{ steps.filter.outputs.components_without_extras }}
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            components_without_extras:
              - sktime/base/**
              - sktime/_contrib/**
              - sktime/benchmarking/**
              - sktime/datatypes/**
              - sktime/distances/**
              - sktime/dists_kernels/**
              - sktime/performance_metrics/**
              - sktime/pipeline/**
              - sktime/proba/**
              - sktime/registry/**
              - sktime/series_as_features/**
              - sktime/split/**
              - sktime/tests/**
              - sktime/utils/**
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
  test_components_without_extras:
    needs: detect_components_without_extras
    name: test all components without extras
    if: ${{ needs.detect.outputs.components_without_extras == 'true' }}
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
        operating-system:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: checkout pull request branch
        uses: actions/checkout@v4
      - name: update local git tracking reference
        run: git remote set-branches origin main
      - name: update local shallow clone
        run: git fetch --depth 1
      - name: create python virtual environment
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: install core, test and all soft dependencies
        run: python3 -m pip install .[all_extras_pandas2,tests]
      - name: run unit tests
        run: python3 -m pytest sktime --ignore sktime/alignment --ignore sktime/annotation --ignore sktime/classification --ignore sktime/clustering --ignore sktime/datasets --ignore sktime/forecasting --ignore sktime/networks --ignore sktime/param_est --ignore sktime/regression --ignore sktime/transformations --matrixdesign True --only_changed_modules True
      - name: test coverage
        uses: codecov/codecov-action@v3
        with:
          flags: ${{ matrix.python-version }},components_without_extras
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
