name: Test with Dev Dependencies

on:
  push:
    branches:
      - feat/dev-deps-test
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  test-dev-deps:
    name: Nightly Dev Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install sktime & dev deps
        run: |-
          pip install .[all_extras,dev]
          pip uninstall -y numba
          pip install --pre --upgrade numpy pandas scikit-learn
          python -c "import numpy, pandas, sklearn; print('numpy', numpy.__version__); print('pandas', pandas.__version__); print('sklearn', sklearn.__version__)"
      - name: Run Smoke Test
        run: pytest sktime/tests/test_softdeps.py
